//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PmssWpfApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10,max")]
        public string TemperatureLevels {
            get {
                return ((string)(this["TemperatureLevels"]));
            }
            set {
                this["TemperatureLevels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000,#FF000000")]
        public string TemperatureColors {
            get {
                return ((string)(this["TemperatureColors"]));
            }
            set {
                this["TemperatureColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r1")]
        public string MonitorRain01Folder {
            get {
                return ((string)(this["MonitorRain01Folder"]));
            }
            set {
                this["MonitorRain01Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\plot")]
        public string MonitorRain03Folder {
            get {
                return ((string)(this["MonitorRain03Folder"]));
            }
            set {
                this["MonitorRain03Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain06Folder {
            get {
                return ((string)(this["MonitorRain06Folder"]));
            }
            set {
                this["MonitorRain06Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain01Levels {
            get {
                return ((string)(this["Rain01Levels"]));
            }
            set {
                this["Rain01Levels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain01Colors {
            get {
                return ((string)(this["Rain01Colors"]));
            }
            set {
                this["Rain01Colors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain03Levels {
            get {
                return ((string)(this["Rain03Levels"]));
            }
            set {
                this["Rain03Levels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain06Levels {
            get {
                return ((string)(this["Rain06Levels"]));
            }
            set {
                this["Rain06Levels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain12Levels {
            get {
                return ((string)(this["Rain12Levels"]));
            }
            set {
                this["Rain12Levels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain24Levels {
            get {
                return ((string)(this["Rain24Levels"]));
            }
            set {
                this["Rain24Levels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain03Colors {
            get {
                return ((string)(this["Rain03Colors"]));
            }
            set {
                this["Rain03Colors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain06Colors {
            get {
                return ((string)(this["Rain06Colors"]));
            }
            set {
                this["Rain06Colors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain12Colors {
            get {
                return ((string)(this["Rain12Colors"]));
            }
            set {
                this["Rain12Colors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain24Colors {
            get {
                return ((string)(this["Rain24Colors"]));
            }
            set {
                this["Rain24Colors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FloodLevels {
            get {
                return ((string)(this["FloodLevels"]));
            }
            set {
                this["FloodLevels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FloodColors {
            get {
                return ((string)(this["FloodColors"]));
            }
            set {
                this["FloodColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DisasterLevels {
            get {
                return ((string)(this["DisasterLevels"]));
            }
            set {
                this["DisasterLevels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DisasterColors {
            get {
                return ((string)(this["DisasterColors"]));
            }
            set {
                this["DisasterColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\product")]
        public string ProductExportFolder {
            get {
                return ((string)(this["ProductExportFolder"]));
            }
            set {
                this["ProductExportFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MonitorRain01Value {
            get {
                return ((int)(this["MonitorRain01Value"]));
            }
            set {
                this["MonitorRain01Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MonitorRain03Value {
            get {
                return ((int)(this["MonitorRain03Value"]));
            }
            set {
                this["MonitorRain03Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MonitorRain06Value {
            get {
                return ((int)(this["MonitorRain06Value"]));
            }
            set {
                this["MonitorRain06Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MonitorRain24Value {
            get {
                return ((int)(this["MonitorRain24Value"]));
            }
            set {
                this["MonitorRain24Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r1-jm")]
        public string MonitorRain01jmFolder {
            get {
                return ((string)(this["MonitorRain01jmFolder"]));
            }
            set {
                this["MonitorRain01jmFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\plot-jm")]
        public string MonitorRain03jmFolder {
            get {
                return ((string)(this["MonitorRain03jmFolder"]));
            }
            set {
                this["MonitorRain03jmFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain06jmFolder {
            get {
                return ((string)(this["MonitorRain06jmFolder"]));
            }
            set {
                this["MonitorRain06jmFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain2405Folder {
            get {
                return ((string)(this["MonitorRain2405Folder"]));
            }
            set {
                this["MonitorRain2405Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain2408Folder {
            get {
                return ((string)(this["MonitorRain2408Folder"]));
            }
            set {
                this["MonitorRain2408Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain2408jmFolder {
            get {
                return ((string)(this["MonitorRain2408jmFolder"]));
            }
            set {
                this["MonitorRain2408jmFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain2408AllFolder {
            get {
                return ((string)(this["MonitorRain2408AllFolder"]));
            }
            set {
                this["MonitorRain2408AllFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain2414Folder {
            get {
                return ((string)(this["MonitorRain2414Folder"]));
            }
            set {
                this["MonitorRain2414Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain2414jmFolder {
            get {
                return ((string)(this["MonitorRain2414jmFolder"]));
            }
            set {
                this["MonitorRain2414jmFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain2414AllFolder {
            get {
                return ((string)(this["MonitorRain2414AllFolder"]));
            }
            set {
                this["MonitorRain2414AllFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain2420Folder {
            get {
                return ((string)(this["MonitorRain2420Folder"]));
            }
            set {
                this["MonitorRain2420Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain2420jmFolder {
            get {
                return ((string)(this["MonitorRain2420jmFolder"]));
            }
            set {
                this["MonitorRain2420jmFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r6")]
        public string MonitorRain2420AllFolder {
            get {
                return ((string)(this["MonitorRain2420AllFolder"]));
            }
            set {
                this["MonitorRain2420AllFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\zd_plot")]
        public string MonitorRain01ZdFolder {
            get {
                return ((string)(this["MonitorRain01ZdFolder"]));
            }
            set {
                this["MonitorRain01ZdFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\edit")]
        public string EditFloodFolder {
            get {
                return ((string)(this["EditFloodFolder"]));
            }
            set {
                this["EditFloodFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\edit")]
        public string EditZilaoFolder {
            get {
                return ((string)(this["EditZilaoFolder"]));
            }
            set {
                this["EditZilaoFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\edit")]
        public string EditDisasterFolder {
            get {
                return ((string)(this["EditDisasterFolder"]));
            }
            set {
                this["EditDisasterFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\edit")]
        public string EditRiverFolder {
            get {
                return ((string)(this["EditRiverFolder"]));
            }
            set {
                this["EditRiverFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\edit")]
        public string EditGTBReferFolder {
            get {
                return ((string)(this["EditGTBReferFolder"]));
            }
            set {
                this["EditGTBReferFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\newecmwf_grib\\rain03\\rain02")]
        public string ECMWF03Folder {
            get {
                return ((string)(this["ECMWF03Folder"]));
            }
            set {
                this["ECMWF03Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\newecmwf_grib\\rain06\\rain01")]
        public string ECMWF06Folder {
            get {
                return ((string)(this["ECMWF06Folder"]));
            }
            set {
                this["ECMWF06Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\newecmwf_grib\\rain12\\rain01")]
        public string ECMWF12Folder {
            get {
                return ((string)(this["ECMWF12Folder"]));
            }
            set {
                this["ECMWF12Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\newecmwf_grib\\rain24\\rain01")]
        public string ECMWF24Folder {
            get {
                return ((string)(this["ECMWF24Folder"]));
            }
            set {
                this["ECMWF24Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\t639\\rain03_3")]
        public string T63903Folder {
            get {
                return ((string)(this["T63903Folder"]));
            }
            set {
                this["T63903Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\t639\\rain06_3_h")]
        public string T63906Folder {
            get {
                return ((string)(this["T63906Folder"]));
            }
            set {
                this["T63906Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\t639\\rain12")]
        public string T63912Folder {
            get {
                return ((string)(this["T63912Folder"]));
            }
            set {
                this["T63912Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\t639\\rain24")]
        public string T63924Folder {
            get {
                return ((string)(this["T63924Folder"]));
            }
            set {
                this["T63924Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\diamond\\hjk\\flood\\output")]
        public string ModelDisaster1Folder {
            get {
                return ((string)(this["ModelDisaster1Folder"]));
            }
            set {
                this["ModelDisaster1Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\diamond\\hjk\\flood\\test2004")]
        public string ModelDisaster2Folder {
            get {
                return ((string)(this["ModelDisaster2Folder"]));
            }
            set {
                this["ModelDisaster2Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Desktop\\Projects\\inform2\\diamond\\zilao\\fxf\\flood-all\\30")]
        public string ModelZilaoFolder {
            get {
                return ((string)(this["ModelZilaoFolder"]));
            }
            set {
                this["ModelZilaoFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\diamond\\floodwarning")]
        public string ModelRiverFolder {
            get {
                return ((string)(this["ModelRiverFolder"]));
            }
            set {
                this["ModelRiverFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\diamond\\flood\\24hr")]
        public string ModelFloodFolder {
            get {
                return ((string)(this["ModelFloodFolder"]));
            }
            set {
                this["ModelFloodFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\diamond\\surface\\valley\\weight_fth")]
        public string ModelAreaRainFolder {
            get {
                return ((string)(this["ModelAreaRainFolder"]));
            }
            set {
                this["ModelAreaRainFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\diamond\\update\\spc\\warning")]
        public string ForcastWeather24Folder {
            get {
                return ((string)(this["ForcastWeather24Folder"]));
            }
            set {
                this["ForcastWeather24Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\diamond\\update\\spc\\pro")]
        public string ForcastWeatherProFolder {
            get {
                return ((string)(this["ForcastWeatherProFolder"]));
            }
            set {
                this["ForcastWeatherProFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Desktop\\Projects\\inform2\\diamond\\update\\flood\\zl")]
        public string ForcastRainQPF24Folder {
            get {
                return ((string)(this["ForcastRainQPF24Folder"]));
            }
            set {
                this["ForcastRainQPF24Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\diamond\\update")]
        public string ForcastRainQPF06Folder {
            get {
                return ((string)(this["ForcastRainQPF06Folder"]));
            }
            set {
                this["ForcastRainQPF06Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r1-jm")]
        public string MonitorRain05DaysFolder {
            get {
                return ((string)(this["MonitorRain05DaysFolder"]));
            }
            set {
                this["MonitorRain05DaysFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\wenxu\\Downloads\\BaiduYun\\inform\\data\\surface\\r1-jm")]
        public string MonitorRain14DaysFolder {
            get {
                return ((string)(this["MonitorRain14DaysFolder"]));
            }
            set {
                this["MonitorRain14DaysFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain05DaysColors {
            get {
                return ((string)(this["Rain05DaysColors"]));
            }
            set {
                this["Rain05DaysColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain05DaysLevels {
            get {
                return ((string)(this["Rain05DaysLevels"]));
            }
            set {
                this["Rain05DaysLevels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain14DaysColors {
            get {
                return ((string)(this["Rain14DaysColors"]));
            }
            set {
                this["Rain14DaysColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rain14DaysLevels {
            get {
                return ((string)(this["Rain14DaysLevels"]));
            }
            set {
                this["Rain14DaysLevels"] = value;
            }
        }
    }
}
